[global]
#
# Run time options
#
assume_two_step         1
logging_level           6
path_trace_enabled      1
follow_up_info          1
tx_timestamp_timeout    40
use_syslog              1
verbose                 0
summary_interval        0
#
# Transport options
#
transportSpecific       0x1
ptp_dst_mac             01:80:C2:00:00:0E
p2p_dst_mac             01:80:C2:00:00:0E
uds_address             /var/run/ptp4l
#
# Default interface options
#
network_transport       L2
delay_mechanism         P2P
time_stamping           hardware

[eth0]

